### ISSUE TITLE
Handle server sending us YAML even if we requested JSON

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA-python-client#12]
@b10n1k reported a bug when accessing a specific endpoint:

    Traceback (most recent call last):
      File "greptestSuite.py", line 64, in <module>
        schd = _get_templates_tests(build)
      File "greptestSuite.py", line 36, in _get_templates_tests
        template = client.openqa_request('GET', 'job_templates_scheduling/129')
      File "/usr/lib/python3.7/openqa_client/client.py", line 174, in openqa_request
        return self.do_request(req, retries=retries, wait=wait)
      File "/usr/lib/python3.7/openqa_client/client.py", line 142, in do_request
        return resp.json()
      File "/home/iob/Envs/suse_py3_env/lib/python3.7/site-packages/requests/models.py", line 897, in json
        return complexjson.loads(self.text, **kwargs)
      File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

the problem is that this endpoint gives us YAML, even though we specifically request JSON (by setting the `ACCEPT` header to `"json"`). I [reported this as an openQA issue](https://progress.opensuse.org/issues/64496), but we should probably handle this for now, by checking the content type and decoding as YAML if the server tells us it sent us YAML.

**Comment by AdamWill** [comment]
Fixed by #13.
